# Generated by Django 5.2.6 on 2025-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategorizePost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("bed", "Bed"),
                            ("sofa", "Sofa"),
                            ("chair", "Chair"),
                            ("table", "Table"),
                            ("dresser", "Dresser"),
                            ("wardrobe", "Wardrobe"),
                            ("bookshelf", "Bookshelf"),
                            ("desk", "Desk"),
                            ("cabinet", "Cabinet"),
                            ("nightstand", "Nightstand"),
                            ("dining_set", "Dining Set"),
                            ("coffee_table", "Coffee Table"),
                            ("tv_stand", "TV Stand"),
                            ("ottoman", "Ottoman"),
                            ("recliner", "Recliner"),
                            ("shelving_unit", "Shelving Unit"),
                            ("bench", "Bench"),
                            ("bar_stool", "Bar Stool"),
                            ("mattress", "Mattress"),
                            ("outdoor_furniture", "Outdoor Furniture"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField()),
                ("discount_price", models.IntegerField(blank=True, null=True)),
                ("stock", models.PositiveIntegerField(default=1)),
                ("brand", models.CharField(blank=True, max_length=50, null=True)),
                ("material", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "width",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("img", models.ImageField(upload_to="furniture_images/")),
                ("description", models.TextField(max_length=500)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
