# Generated by Django 5.2.6 on 2025-09-13 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorizepost",
            name="slug",
        ),
        migrations.AddField(
            model_name="categorizepost",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="furniture_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="brand",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="color",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="depth",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="height",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="material",
            field=models.CharField(blank=True, default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="categorizepost",
            name="width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
